# Custom deployment manifest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-dpl
  labels:
    app: mp-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mp-dpl
  template:
    metadata:
      labels:
        app: mp-dpl
    spec:
      containers:
      - name: message-producer
        image: rg532/spring-k8s-demo:message-producer
        imagePullPolicy: Always
        ports:
        - containerPort: 8081